POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Peter Ang",
    "number": "999"
}


###
GET http://localhost:3001/api/persons/1

###
GET http://phonebook-f9az.onrender.com/

###
POST http://phonebook-f9az.onrender.com/api/persons
content-type: application/json

{
    "name": "Peter Ang",
    "number": "999"
}